name: Flutter RC CI

on:
  pull_request:
    branches:
      - rc

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "17"

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.38.2"
          channel: "stable"
          cache: true

      - name: Flutter version
        run: flutter --version

      - run: flutter pub get
      - run: flutter analyze
      - run: flutter test
      - run: flutter build apk --flavor dev --release
